# Generated by Django 2.0.7 on 2018-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thum',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
